version: "3.8"

services:
  server:
    image: vuong676/devops-intern-assignment-ntv:${VERSION}
    container_name: server
    networks:
      - "devops-internship"

  webserver:
    image: nginx:1.27.0-alpine
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./webserver/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - "devops-internship"

networks:
  devops-internship:
    driver: bridge
