name: CI/CD Pipeline

on:
  push:
    branches: ["feature"]
  pull_request:
    branches: ["feature"]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./src

      - name: Run tests
        run: npm test --prefix ./src

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  cd:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH__KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOSTNAME: ${{ secrets.HOSTNAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i "private_key.pem" ${USER_NAME}@${HOSTNAME}
