name: CI/CD Pipeline

on:
  push:
    branches: ["feature"]
  pull_request:
    branches: ["feature"]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./src

      - name: Run tests
        run: npm test --prefix ./src

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  cd:
    name: CD Pipeline
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull vuong676/devops-intern-assignment-ntv:48e830b
