name: CI/CD Pipeline

on:
  push:
    branches: ["feature"]
  pull_request:
    branches: ["feature"]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./src

      - name: Run tests
        run: npm test --prefix ./src

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  cd:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOSTNAME }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "cd goldenowl-devops-internship-challenge"

      - name: cleanup
        run: rm -rf ~/.ssh
