name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    steps:
      # Step to checkout the code from the repository
      - uses: actions/checkout@v4

      # Step to set up Node.js with cache enabled
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./src

      - name: Run tests
        run: npm test --prefix ./src
