name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix ./src

      - name: Run tests
        run: npm test --prefix ./src

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS}}
